"""post-table

Revision ID: 155a5b21c527
Revises: f44007e22cb0
Create Date: 2024-12-07 12:31:12.707807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '155a5b21c527'
down_revision: Union[str, None] = 'f44007e22cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('attachmentID', sa.Integer(), nullable=False),
    sa.Column('postID', sa.Integer(), nullable=True),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('filePath', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['postID'], ['post.postID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachmentID')
    )
    op.create_index(op.f('ix_attachment_attachmentID'), 'attachment', ['attachmentID'], unique=False)
    op.create_table('keyword',
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['postID'], ['post.postID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postID', 'name')
    )
    op.alter_column('follow', 'follow_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('follow_ibfk_1', 'follow', type_='foreignkey')
    op.drop_constraint('follow_ibfk_2', 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'user', ['userID'], ['userID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow', 'user', ['followID'], ['userID'], ondelete='CASCADE')
    op.drop_constraint('like_ibfk_2', 'like', type_='foreignkey')
    op.drop_constraint('like_ibfk_1', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'user', ['userID'], ['userID'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like', 'post', ['postID'], ['postID'], ondelete='CASCADE')
    op.alter_column('post', 'create_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('post', 'update_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['userID'], ['userID'], ondelete='CASCADE')
    op.drop_column('post', 'categoryname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('categoryname', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['userID'], ['userID'])
    op.alter_column('post', 'update_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('post', 'create_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_ibfk_1', 'like', 'post', ['postID'], ['postID'])
    op.create_foreign_key('like_ibfk_2', 'like', 'user', ['userID'], ['userID'])
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key('follow_ibfk_2', 'follow', 'user', ['userID'], ['userID'])
    op.create_foreign_key('follow_ibfk_1', 'follow', 'user', ['followID'], ['userID'])
    op.alter_column('follow', 'follow_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_table('keyword')
    op.drop_index(op.f('ix_attachment_attachmentID'), table_name='attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
