"""New

Revision ID: f44007e22cb0
Revises: e7ae8f7c57b4
Create Date: 2024-12-03 16:41:40.351451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44007e22cb0'
down_revision: Union[str, None] = 'e7ae8f7c57b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('introduce', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'introduce')
    # ### end Alembic commands ###
